### ISSUE TITLE
 CodeXL_2.3-605 searching for libpng12

### ISSUE THREAD

**Issue by reanimastudios** [GPUOpen-Tools/CodeXL#129]
Debian has long since removed libpng12 and now only available as an ARM debport. This keeps CodeXL from loading.

mdriftmeyer@horus:/opt/CodeXL_2.3-605$ ./CodeXL
/opt/CodeXL_2.3-605/./CodeXL-bin: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

Can we get current and use libpng16?

**Comment by preda** [comment]
I have the same problem on Ubuntu 16.10:
~/xl$ /opt/CodeXL_2.3-605/CodeXL
/opt/CodeXL_2.3-605/CodeXL-bin: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

**Comment by SilverNexus** [comment]
On Debian testing (Stretch) the error is a little more cryptic (something involving a missing PNG12_0 in the so file instead of the so file being missing entirely), but the same problem exists. Might be the difference between Debian hedging to fool most things (if libpng16 is backwards-compatible with libpng12) and Ubuntu just looking forward (just a guess), or possibly leftover cruft from the transition between libraries.

Either way, some degree of support for libpng16 should exist in the binaries.

**Comment by chesik-amd** [comment]
This should no longer be an issue in the CodeXL 2.6 release
