### ISSUE TITLE
Latest release will not install on Ubuntu with ROCm

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-Tools/CodeXL#161]
For .deb file, when running `sudo dpkg -i /path/to/deb/file` I get:

  CC [M]  /usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.o
/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.c:198:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault = pp_anon_inode_mmap_fault,
              ^
/usr/src/amdtPwrProf-6.01/src/AMDTPwrProfSharedMemOps.c:198:14: note: (near initialization for ‘sharedBuffer_mmap_vm_ops1.fault’)
cc1: some warnings being treated as errors

**Comment by MikalaiDrabovich** [comment]
I have the same error on 4.11.0-kfd-compute-rocm-rel-1.6-148, with sudo dpkg -i codexl_2.5-25_amd64.deb

**Comment by nabar** [comment]
It occurs with the kernels newer than 4.10.
You can fix it with the following patches if you use the kernel newer than 4.10:

1. In src/AMDTPwrProfSharedMemOps.c:
static int pp_anon_inode_mmap_fault(struct vm_fault* vmf)
instead
static int pp_anon_inode_mmap_fault(struct vm_area_struct* vma, struct vm_fault* vmf)

In this function:
add the following line just after the declaration of the local variables:
struct vm_area_struct * vma = vmf->vma;

2. In inc/AMDTPwrProfCoreUtils.h
Add the following line just after all the include files.
#include <linux/uaccess.h>

3. In inc/AMDTRawDataFileHeader.h
Change the following lines:
Add
static const wchar_t g_RawFileMagicStr[] = {'_', 'R', 'A', 'W', 'H', 'D', 'R', '_'};
instead of
static const wchar_t g_RawFileMagicStr[] = L"_RAWHDR_";

**Comment by boxerab** [comment]
Time for a new release ?

**Comment by MikalaiDrabovich** [comment]
Thanks nabar! Please take a look at https://github.com/GPUOpen-Tools/CodeXL/pull/163
or just clone from https://github.com/MikalaiDrabovich/CodeXL

**Comment by kruftindustries** [comment]
I have the same error on 4.11.0-kfd-compute-rocm-rel-1.6-180, with sudo dpkg -i codexl_2.5-25_amd64.deb.

I was unable to build CodeXL successfully. GpuProfiler problems, couldn't find the backend_build.sh script...

I did have to alter nabar's change because my compiler griped about an empty char constant:
`static const wchar_t g_RawFileMagicStr[] = {'\0', 'R', 'A', 'W', 'H', 'D', 'R', '\0'};`

`git clone --recursive https://github.com/GPUOpen-Tools/CodeXL` for those who made it this far :)

**Comment by MikalaiDrabovich** [comment]
@kruftindustries what do you mean by "deleting everything" - including patches ?

**Comment by kruftindustries** [comment]
Yes. 2nd time I re-applied patches and I'm getting an error about a .S
file, I must have forgotten to use a flag for my glibc

**Comment by kruftindustries** [comment]
I ended up reinstalling and not issuing apt-get dist-upgrade this time, CodeXL works great from the .deb release ;)

**Comment by PolarNick239** [comment]
+1 - Ubuntu 16.04, kernel 4.13.0-36

Thanks a lot, nabar!

Just for the sake of completeness - instead of this:

> 3. In inc/AMDTRawDataFileHeader.h
> Change the following lines:
> Add
> static const wchar_t g_RawFileMagicStr[] = {'', 'R', 'A', 'W', 'H', 'D', 'R', ''};
> instead of
> static const wchar_t g_RawFileMagicStr[] = L"RAWHDR";

Should be this:

> 3. In inc/AMDTRawDataFileHeader[.h
> Change the following lines:
> Add
> `static const wchar_t g_RawFileMagicStr[] = {'_', 'R', 'A', 'W', 'H', 'D', 'R', '_'};`
> instead of
> `static const wchar_t g_RawFileMagicStr[] = L"_RAWHDR_";`

**Comment by pwasiewi** [comment]
I acknowledge at least module compilation for 4.13.0-36-generic #40~16.04.1-Ubuntu:
```
mkdir debcodexl
dpkg-deb -R  codexl_2.5-25_amd64.deb debcodexl
cd debcodexl/opt/CodeXL_2.5-25
tar zxvf CodeXLPwrProfDriverSource.tar.gz
rm CodeXLPwrProfDriverSource.tar.gz
#apply changes mentioned earlier to amdtPwrProf-6.01/Makefile 
#and amdtPwrProf-6.01/inc/AMDTRawDataFileHeader.h
tar zcvf CodeXLPwrProfDriverSource.tar.gz amdtPwrProf-6.01
rm -rf amdtPwrProf-6.01 
rm codexl_2.5-25_amd64.deb
dpkg-deb -b debcodexl codexl_2.5-25_amd64.deb
apt remove codexl -y; dpkg -i codexl_2.5-25_amd64.deb
```

the patch for amdtPwrProf-6.01
```
diff -r amdtPwrProf-6.01/inc/AMDTPwrProfCoreUtils.h amdtPwrProf-6.01.new/inc/AMDTPwrProfCoreUtils.h
32c32
< #include <asm/uaccess.h>
---
> #include <linux/uaccess.h>
diff -r amdtPwrProf-6.01/inc/AMDTRawDataFileHeader.h amdtPwrProf-6.01.new/inc/AMDTRawDataFileHeader.h
86c86,87
< static const wchar_t g_RawFileMagicStr[] = L"_RAWHDR_";
---
> //static const wchar_t g_RawFileMagicStr[] = L"_RAWHDR_";
> static const wchar_t g_RawFileMagicStr[] = {'_', 'R', 'A', 'W', 'H', 'D', 'R', '_'};
diff -r amdtPwrProf-6.01/Makefile amdtPwrProf-6.01.new/Makefile
36c36
< EXTRA_CFLAGS=-I$(PWD)/inc -DKERNEL_MODULE -DLINUX -D_LINUX 
---
> EXTRA_CFLAGS=-I$(PWD)/inc -DKERNEL_MODULE -DLINUX -D_LINUX -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types
```

**Comment by aalok-agarwal** [comment]
Hi Everyone, 
Thanks for analyzing the issue and providing pull requests and patches.
We had made the fixes similar to pull request #163 via the commit id: 36c267db1bc4af4c6921edd845fefb5863297b1c which is available on the latest repo. This fix is not available on CodeXL 2.5-25 release source code, as it was released prior to this commit.

You may apply the 36c267d patch to CodeXL 2.5-25 source code and build it.
Or, you may git-clone the latest CodeXL source (which already includes 36c267d) and build it.

Please try one of the above options and let us if the issue is still observed.

We noticed that some other/new PowerProfile driver compilation issues with kernel 4.13.0-36. We are looking into it and we will submit a fix ASAP.

Regards,
Aalok

**Comment by PolarNick239** [comment]
Thanks for your response, but workaround of building CodeXL from source code is not easy. I tried to do so as soon as I faced these problems in released version, but Ubuntu 16.04 + gcc 5.4 can't compile CodeXL due to (if I remember correctly) warnings like in Issue #183.

So in my opinion new release with support for new kernels is important at least while compilation from source code is so hard.

**Comment by aalok-agarwal** [comment]
Hi PolarNick239, 
Commit 36c267d changes are for the power profiler driver sources, so you can skip building the complete CodeXL source code. Only power profiler driver sources needs to be re-build and re-installed.

Please follow the below steps to build and to install drivers in your machine.

1. git-clone the CodeXL latest repo from master branch. (Latest source already includes the required commit.)

2. Just re-create the driver source package using the following commands. No need to do complete source build.
`$ cd  CodeXL/Components/PowerProfiling/Backend/AMDTPowerProfilingDrivers/Linux/`
`$ ./createPwrProfSourcePkg.sh  PUBLIC`
(CodeXLPwrProfDriverSource.tar.gz file gets created here.)

3. Copy the source package created in step 2 to the directory containing binaries for CodeXL_Linux_x86_64_2.5.25.
`$ cp CodeXLPwrProfDriverSource.tar.gz /home/xyz/CodeXL_Linux_x86_64_2.5.25`

4. Install the driver using the following command.
`$ cd /home/xyz/CodeXL_Linux_x86_64_2.5.25`
`$ sudo ./CodeXLPwrProfDriver.sh install`

**Comment by PolarNick239** [comment]
Oh, thanks, I already did it. Obviously I confused this problem with driver with my another problem with compilation whole CodeXL. Nevermind, thank you.

**Comment by aalok-agarwal** [comment]
Thanks

**Comment by madMAx43v3r** [comment]
Could you please make a new release that works with Ubuntu 18.04?

```
Installing CodeXL Power Profiler driver.
Installing AMD CodeXL Power Profiler Linux kernel module version 6.01.
Makefile:76: recipe for target 'dkms' failed
make: *** [dkms] Error 10
ERROR: CodeXL Power Profiler driver installation failed.
```

**Comment by kpenujee** [comment]
Hi,
For CPU and Power profiling, AMD has an exclusive tool called "AMD uProf". It works on Ubuntu 18.04 too. Following is the link to the tool:
https://developer.amd.com/amd-uprof/


Thanks,
Kalyan P

**Comment by madMAx43v3r** [comment]
Thanks for the hint, but I need to profile OpenCL on GPU devices (Vega64 to be specific). I managed to get the basic performance counters with https://github.com/GPUOpen-Tools/RCP now. But still AMD should provide a tool that matches NVVP if they want to compete with CUDA.

**Comment by PolarNick239** [comment]
+1 for new release. It is nearly impossible to install amdgpu-pro on old kernels (which compatible with CodeXL), so I updated to 16.04.5 with 4.15.0 but now I can't install CodeXL.

Moreover - CodeXL more than a year has another major issue - it segfaults in case of GPU profiling  with default options (https://github.com/GPUOpen-Tools/CodeXL/issues/179#issuecomment-360601895 - workaround to disable occupancy profiling, which is major feature itself).

**Comment by mahmoodn** [comment]
@kpenujee 
Hi, I wasn't able to install uprof on 18.04. I asked the question in the [forum](https://community.amd.com/message/2916934).
Do you have any idea about that?
