### ISSUE TITLE
Feature request: display a diff of two different profile runs

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-Tools/CodeXL#170]
It is a common workflow to run CodeXL, then change something in the kernel, then run it again and see what changed. Since each profile run has many different counters, it would be helpful to easily make a diff between two, to see what has changed.  Thanks.

**Comment by mcleary** [comment]
CodeXL has a number of different profiling options. Are you talking about GPU Profiling, Power Profiling, CPU Profiling, Application Timeline Profiling or other kinds of profiler?

Since CodeXL is now an open source tool I would suggest you to post at least a mock on what do you have in mind and how the diff should be displayed on the screen.

**Comment by boxerab** [comment]
Thanks. This would be for GPU profiling.  The most intuitive I think would be for the user to highlight two items in the "GPU: Performance counters" list on the left, right click and choose "diff" and they would see the differences in the "Performance counters" pane, with +- to indicate delta for each setting. Some columns would be disabled because the diff is not meaningful, such as "Execution Order" for example.

**Comment by mcleary** [comment]
I think this is a good idea and a common use case when profiling applications. Usually, you want to see what changed. Do not expect this feature to be included anytime soon since looks like CodeXL is slowly becoming several different tools, however, this is something I am looking to try to implement for the GPU profiler.
