### ISSUE TITLE
Interpretation of HSA counters: VALUBusy and MemUnitBusy

### ISSUE THREAD

**Issue by apanqasem** [GPUOpen-Tools/CodeXL#211]
This issue is not directly tied to CodeXL but I am posting here because I think someone here will have the answer. 

We are running some micro-kernel experiments to evaluate data placement trade-offs on a discrete GPU node (Vega 10 + Thread Ripper) with ROCM (1.7) support.  

To estimate the compute/memory intensity of kernels, we are looking at the VALUBusy, MemUnitBusy, MemUnitStalled, SALUBusy and VALUUtilization counters. In one of the microkernels, we progressively increase the theoretical occupancy by increasing the number of available wavefronts. As expected, increasing the theoretical occupancy shows a marked decrease (from 75% down to 25%) in both MemUnitBusy and MemUnitStalled counters. However, there is no discernible change in either VALUBusy or the execution time of the kernel.  So, I am guessing that the MemUnitStalls are being converted to some other kind of stall in the system. 

My question is, is there a way to figure out, by some combination of counters, where these stalls are occurring (FetchUnit perhaps?)? I know that VALUBusy, SALUBusy and MemUnitBusy don't up to a 100 for many kernels. Can we say, 100 - (VALUBusy + SALUBusy + MemUnitBusy) = X? Or is X composed of many different components?

As further clarification, FetchSize, WriteSize and L2CacheHit remains the same for different versions of the micro-kernel. Also, we are using HC code, so we can't get the dynamic kernel occupancy using the counters.

**Comment by jlgreathouse** [comment]
Without seeing your kernels, I'm really not sure if it's possible to debug what you're seeing. For instance, increasing occupancy shouldn't, as far as I can guess, descrease MemUnitBusy or MemUnitStalled.

MemUnitBusy is the number of cycles when there is work in the texture address (TA) units divided by the total number of cycles your kernel takes. This is defined [in this document in GPA](https://github.com/GPUOpen-Tools/GPA/blob/v3.1/Src/PublicCounterCompilerInputFiles/PublicCounterDefinitionsComputeGfx9.txt#L193). The TA is essentially the address generation unit for a CU's vector memory loads/stores. Adding more wavefronts per compute unit should not decrease the number of cycles when you are issuing memory instructions into the memory logic -- I don't know why you would expect that, and I don't know why you're seeing it.

[MemUnitStalled](https://github.com/GPUOpen-Tools/GPA/blob/v3.1/Src/PublicCounterCompilerInputFiles/PublicCounterDefinitionsComputeGfx9.txt#L203) is **not** the amount of time that the core is stalled on memory instructions, but rather (based on the definition I've linked) it is related to the amount of time that the TCP (the actual L1 data cache) back-pressures the address generation unit to prevent further memory operations from going into the cache. This may happen, for instance, because you have too many outstanding loads waiting to come back, and the TCP cannot handle more. Or if you have released a few very uncoalesced loads that take up a lot of space in the memory buffers (essentially the MSHRs for the L1 cache).

Note that the L1D stalling the address generation logic does *not* mean that the entire CU is stalled. Other wavefronts that can potentially issue VALU, SALU, SMEM, branch, or internal instructions (like s_nop) can continue to issue if they are able. The only thing this back-pressure signal means is that further VMEM operations will be unable to issue because the hardware cannot hold more of them. As such, I would also not expect this to go down if all you're doing is adding more wavefronts in the kernel.

To directly address some of your later questions, no, you can't really make any correlation between any of the Busy counters, nor can you directly make correlations between any of the Stall counters (nor any combinations thereof).

Busy counters are "a cycle you're issuing work into one of the many units". Presentations about the GCN microarchitecture (such as the [Crash Course by Layla Mah](https://www.slideshare.net/DevCentralAMD/gs4106-the-amd-gcn-architecture-a-crash-course-by-layla-mah) discuss how it's possible for us to issue work from multiple waves in a single cycle, so long as each wave is issuing a different type of instruction. For instance, I can issue a VALU instruction from wavefront 0, an SALU instruction from wavefront 1, and a VMEM instruction from wavefront 2. If this kind of thing happens every cycle the GPU is active, VALUBusy, SALUBusy, and MemUnitBusy would all be 100%.

On the other hand, just because one unit is stalled (and thus all wavefronts whose next instructions would require that unit will be stalled) does not mean that all of the wavefronts are stalled. If the VMEM unit is back-pressuring all waves that have VMEM instructions ready to issue, other wavefronts with VALU instructions ready to issue may continue to go. As such, the Stalled counters do not necessarily mean that the CU was making no progress that cycle, only that some units were causing some amount of back-pressure.

It may be the case that your kernels, however you're writing them, are being compiled very differently between your tests. I would recommend looking at the assembly dumps by setting the environment variable KMDUMPISA=1 while compiling your HC code.

**Comment by apanqasem** [comment]
@jlgreathouse thanks very much for the response. 

The performance counter reference I was using is [this one](https://github.com/GPUOpen-Tools/GPA/blob/master/docs/source/graphicscountertables.rst). It doesn't give the level of detail as the other document that you cited. 

I am running an extended version of [BabelStream](https://github.com/UoB-HPC/BabelStream). The kernels stress different parts of the GPU  to derive _effective_ limits for bandwidth, operational intensity, occupancy etc for host and device-placed data structures. I haven't looked at the assembly output yet but the kernels themselves are fairly simple and we had been able to "verify" some of the limits (e.g., bandwidth saturation points) with the counters. Of course, now with this new (and corrected) definition, all of that falls apart and we need re-evaluate our analysis. 

We we going by Indrani Paul's [dissertation work](https://smartech.gatech.edu/bitstream/handle/1853/53547/PAUL-DISSERTATION-2015.pdf) where she uses VALUBusy and MemUnitBusy to get a measure of the compute intensity of the kernel. 

Our thinking was that the availability of additional wavefronts (and additional computation) will allows us to hide some of the latency due to memory unit stalls. Since MemUnitStalls are included in MemUnitBusy, we expected MemUnitBusy to decrease when occupancy increases. This strategy worked for other platforms (with different counters of, course). But it sounds like MemUnitStalls cannot be overlapped with computation. It's purely a function of the requested bandwidth to TCP. So, now I have no idea why we are seeing a decrease in MemUnitStalls when operational intensity or occupancy increases. We need to go back and re-evaluate our kernels.
