### ISSUE TITLE
Strange crashes in CodeXL

### ISSUE THREAD

**Issue by karloballa** [GPUOpen-Tools/CodeXL#245]
Everything worked fine until some point after which CodeXL stopped to work in the profile mode (the program that I wanted to profile simply crashes). I reinstalled Windows, drivers, CodeXL, Visual Studio and still have the same problem. 

The program that I want to profile crashes about here: cl::Platform::get(&platforms) -> cl_int err = ::clGetPlatformIDs(0, NULL, &n) with the error: 

Exception thrown at 0x00007FFBFED71149 (OpenCL.dll) in Test.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

From Visual Studio or as a standalone program everything works fine but crashes in CodeXL.

Every help would be appreciated.

**Comment by mcleary** [comment]
Does `clinfo` still work?

**Comment by karloballa** [comment]
Yes. It seems to me that clinfo works like it should work
(in fact, prints the same platform twice ?!)

**Comment by chesik-amd** [comment]
I ran into this on a couple of different Windows systems.

The profiler problem and the fact that you see 2 platforms in clinfo have the same root cause.  Until an updated driver that fixes this issue is released, there is a workaround that will take care of both issues.

The workaround that worked for me was to modify the Windows registry using regedit and rename the following registry key: **HKEY_LOCAL_MACHINE\SOFTWARE\Khronos**

On the systems where I ran into this issue, once I renamed that key, clinfo no longer printed out two platforms, and the profiler started working correctly.

I'm not aware of any side effects of this workaround, but please use it at your own risk.

**Comment by mcleary** [comment]
Since you have two platforms with the same name, I believe you have an entry pointing to an invalid OpenCL implementation. Do a clean driver installation and it should fix the problem

**Comment by karloballa** [comment]
Ok, I renamed the key in the registry and reset the computer. After that, clinfo crashes. Then I reinstalled the driver and now clinfo displays only one platform and two devices (CPU+GPU). Unfortunately, the problem in CodeXL still exists. The profiled program crashes at the same line cl::Platform::get(& platforms) :(

**Comment by mcleary** [comment]
> I ran into this on a couple of different Windows systems.
> 
> The profiler problem and the fact that you see 2 platforms in clinfo have the same root cause. Until an updated driver that fixes this issue is released, there is a workaround that will take care of both issues.
> 
> The workaround that worked for me was to modify the Windows registry using regedit and rename the following registry key: **HKEY_LOCAL_MACHINE\SOFTWARE\Khronos**
> 
> On the systems where I ran into this issue, once I renamed that key, clinfo no longer printed out two platforms, and the profiler started working correctly.
> 
> I'm not aware of any side effects of this workaround, but please use it at your own risk.

This problem where `clinfo` reports two platforms with the same just happened to me.

After spending the day investigating the issue I decided to compile both the ICD loader and `clinfo` myself. After running the latest versions I realized that both binaries, `clinfo` and `OpenCL.dll` provided by AMD are outdated. The ICD loader does not look in the right places and mixes things. That's why the same platform is reported twice. 

The ICD loader that I built from source is working just fine. To be fair, Intel is doing the same thing with their bundled ICD Loader. The [ICD loader](https://github.com/KhronosGroup/OpenCL-ICD-Loader) is an open source project so it should be too difficult to install the latest version with the drivers

**Comment by karloballa** [comment]
I reinstalled everything with latest adrenaline driver, and now CodeXL works. However, it seems to me that the compiler in the latest driver is hell broken, but that is another story...

Thanks for the help.
