### ISSUE TITLE
Failure compiling on Ubuntu

### ISSUE THREAD

**Issue by malcolmroberts** [GPUOpen-Tools/CodeXL#4]
Hello.

I followed the instructions to build on Ubuntu (x86_64, 15.10) and I got to the point where I launched backend_build.sh.  It seems to have problems finding CXL_init .  The contents of GpuProfilerBackend_Build.log are included below.

Thanks for your help!

~Malcolm

=====Building GPU Profiler Backend======
# Building infra projects
# Build arguments passed to scons: 

----------- Start building --------------- 
# Wed Apr 20 13:11:52 CEST 2016

scons -C /home/XXX/repo/CodeXL/CodeXL/Components/GpuProfiling/Build/../Build CXL_prefix=/home/XXX/repo/CodeXL/CodeXL/Components/GpuProfiling/Build/.. CXL_build_type=static 
scons: Reading SConscript files ...
ImportError: No module named CXL_init:
  File "/home/XXX/repo/CodeXL/CodeXL/Components/GpuProfiling/Build/SConstruct", line 6:
    from CXL_init import *
# **\* ERROR during the build of the 64 bit framework ***

scons -C /home/XXX/repo/CodeXL/CodeXL/Components/GpuProfiling/Build/../Build CXL_prefix=/home/XXX/repo/CodeXL/CodeXL/Components/GpuProfiling/Build/.. CXL_arch=x86 CXL_build_type=static 
scons: Reading SConscript files ...
ImportError: No module named CXL_init:
  File "/home/XXX/repo/CodeXL/CodeXL/Components/GpuProfiling/Build/SConstruct", line 6:
    from CXL_init import *
# **\* ERROR during the build of the 32 bit framework ***

----------- End building ----------------- 
# Wed Apr 20 13:11:53 CEST 2016

**Comment by giladyarnitzky** [comment]
Can you please validate that in the same directory as the backend_build.sh that you have a file named CXL_init.py which is a link to a the file ../../../../common/Src/Scons/CXL_init.py and that you also have that file which is in the "common" sub-module.
If you don't:
Open a command prompt, navigate to the repo root directory and type the following commands:
git submodule init
git submodule update

**Comment by malcolmroberts** [comment]
Thanks for your reply.  I had some time today to try, and this solved the problem of running backend_build.sh

Now, following the build instructions, I changed directory to CodeXL/CodeXL/Util/linux, I get the following error:

$ ./buildCodeXLFullLinuxProjects  
AMD_CODEXL dir = /home/XXX/repo/CodeXL/CodeXL


Building all Linux projects
===========================
Build arguments passed to scons: 


========================================== 
----------- Start building --------------- 
cd /home/XXX/repo/CodeXL/CodeXL
scons CXL_common_dir=/home/XXX/repo/CodeXL/CodeXL/../Common CXL_prefix=/home/XXX/repo/CodeXL/CodeXL/../ 
Tue Apr 26 11:58:55 CEST 2016
========================================== 
scons: Reading SConscript files ...
Warning: CXL_common_dir not available. Using SConstruct variable.
KeyError: 'JAVA_HOME':
  File "/home/XXX/repo/CodeXL/CodeXL/SConstruct", line 294:
    libJvmtiProfileAgent_Obj = SConscript('Components/CpuProfiling/ProfilingAgents/AMDTJvmtiAgent/SConscript', variant_dir=obj_variant_dir+'/AMDTJvmtiAgent', duplicate=0)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/home/XXX/repo/CodeXL/CodeXL/Components/CpuProfiling/ProfilingAgents/AMDTJvmtiAgent/SConscript", line 17:
    os.environ['JAVA_HOME'] + '/include',
  File "/usr/lib/python2.7/UserDict.py", line 23:
    raise KeyError(key)
*** ERROR during the build of this subcomponent ***
========================================== 
----------- End building ----------------- 
Tue Apr 26 11:58:56 CEST 2016
========================================== 
*** ERROR ***
*** the build failed - see the logs for details ***

**Comment by giladyarnitzky** [comment]
You'll need to define the location of your Java (I need to check if this is another step that needs to be added to the explanations)
But for now do
export JAVA_HOME=the location of your java (for example it might be for latest java on a centos machine /usr/java/jdk1.8.0_77)

**Comment by malcolmroberts** [comment]
Hello again!

Ok, I did an

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/bin

and then ran

cd /home/XXX/repo/CodeXL/CodeXL/Util/linux
./buildCodeXLFullLinuxProjects

and got the following errors:

AMD_CODEXL dir = /home/XXX/repo/CodeXL/CodeXL


Building all Linux projects
===========================
Build arguments passed to scons: 


========================================== 
----------- Start building --------------- 
cd /home/XXX/repo/CodeXL/CodeXL
scons CXL_common_dir=/home/XXX/repo/CodeXL/CodeXL/../Common CXL_prefix=/home/XXX/repo/CodeXL/CodeXL/../ 
Fri Apr 29 13:30:10 CEST 2016
========================================== 
scons: Reading SConscript files ...
Warning: CXL_common_dir not available. Using SConstruct variable.
Copying Driver Installation Files
./build/x86_64
OSError: [Errno 2] No such file or directory: '/home/XXX/repo/CodeXL/CodeXL/../Common/Lib/AMD/GPUPerfAPI/2_20/Bin-Internal/Linx64':
  File "/home/XXX/repo/CodeXL/CodeXL/SConstruct", line 445:
    GpuProf_Obj = SConscript('Components/GpuProfiling/AMDTGpuProfiling/SConscript', variant_dir=obj_variant_dir+'/AMDTGpuProfiling', duplicate=1)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/home/XXX/repo/CodeXL/CodeXL/variant_release/AMDTGpuProfiling/SConscript", line 28:
    initCommonLibAmd (GPUProf_env, CXL_lib_common_amd_deps)
  File "/home/XXX/repo/CodeXL/CodeXL/CXL_init.py", line 745:
    files = os.listdir(lib_path)
*** ERROR during the build of this subcomponent ***
========================================== 
----------- End building ----------------- 
Fri Apr 29 13:30:11 CEST 2016
========================================== 
*** ERROR ***
*** the build failed - see the logs for details ***

**Comment by kpontzolkova** [comment]
hello every one,

I'm trying to build CodeXL(ubuntu14.04)

when running backend_build.sh i getr the following errors:

=====Building GPU Profiler Backend======

Building infra projects
===========================
Build arguments passed to scons: 
========================================== 
----------- Start building --------------- 
Thu May 12 10:53:24 EEST 2016
========================================== 
scons -C /homes/kpontzolkova/Downloads/git/CodeXL/CodeXL/Components/GpuProfiling/Build/../Build CXL_prefix=/homes/kpontzolkova/Downloads/git/CodeXL/CodeXL/Components/GpuProfiling/Build/.. CXL_build_type=static 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o /homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.os -c -fPIC -Wall -Werror -Wextra -g -fmessage-length=0 -Wno-unknown-pragmas -pthread -DGDT_BUILD_SUFFIX= -std=c++11 -O3 -DNDEBUG -DGDT_PUBLIC -I/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools -I/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src -I/homes/kpontzolkova/Downloads/git/CodeXL/CommonProjects -I/homes/kpontzolkova/Downloads/git/CodeXL/Common /homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.cpp
/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.cpp:12:64: fatal error: AMDTBaseTools/Include/gtIAllocationFailureObserver.h: No such file or directory
 #include <AMDTBaseTools/Include/gtIAllocationFailureObserver.h>
                                                                ^
compilation terminated.
scons: *** [/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.os] Error 1
scons: building terminated because of errors.
*** ERROR during the build of the 64 bit framework ***
========================================== 
scons -C /homes/kpontzolkova/Downloads/git/CodeXL/CodeXL/Components/GpuProfiling/Build/../Build CXL_prefix=/homes/kpontzolkova/Downloads/git/CodeXL/CodeXL/Components/GpuProfiling/Build/.. CXL_arch=x86 CXL_build_type=static 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o /homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.os -c -fPIC -Wall -Werror -Wextra -g -fmessage-length=0 -Wno-unknown-pragmas -pthread -DGDT_BUILD_SUFFIX= -std=c++11 -O3 -DNDEBUG -m32 -DGDT_PUBLIC -I/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools -I/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src -I/homes/kpontzolkova/Downloads/git/CodeXL/CommonProjects -I/homes/kpontzolkova/Downloads/git/CodeXL/Common /homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.cpp
/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.cpp:12:64: fatal error: AMDTBaseTools/Include/gtIAllocationFailureObserver.h: No such file or directory
 #include <AMDTBaseTools/Include/gtIAllocationFailureObserver.h>
                                                                ^
compilation terminated.
scons: *** [/homes/kpontzolkova/Downloads/git/CodeXL/Common/Src/AMDTBaseTools/src/gtIAllocationFailureObserver.os] Error 1
scons: building terminated because of errors.
*** ERROR during the build of the 32 bit framework ***
========================================== 
----------- End building ----------------- 
Thu May 12 10:53:34 EEST 2016
========================================== 





it seems that it doent see gtIAllocationFailureObserver.h file, but i confirmed that it exist.

Any thoughts on how to solve it?

**Comment by kpontzolkova** [comment]
Java version should be java 8!!!

**Comment by tangjie77wd** [comment]
@malcolmroberts @giladyarnitzky @kpontzolkova @rys @perhaad 
Hello!I create projects with OpenCL on linux . My machine : CentOS 7.3+eclipse + AMD Rx560 + amdgpu-pro-17.30-465504 + CodeXL_Linux_x86_64_2.4.60 .

1.    After I installed all tools above , go into the 'CodeXL_Linux_x86_64_2.4.60' folder and open a terminal ,run the command : ./CodeXL ,then CodeXL gui will appear .
2.    Click the 'Help' menu and then click 'Load the Teapot Sample' .
3.   Click the 'Profile' menu and then clike 'GPU:Performance Counters' .
4.    Press 'F5' on your keyboard and wait for a while.
5.    Close the 'AMD Teapot Example' gui and wait for a while , you will see many performance indicators in the CodeXL gui.
But I have a question these days : the Teapot sample is provided by CodeXL not myself (It exists in CodeXL as a 'CodeXL Teapot.cxl' file ,so we can load it directly in CodeXL. ) , how can i use CodeXL to test the performance of my own OpenCL projects (.cpp file and .cl file) written in the eclipse ( no .cxl file )? Any help will be much appriciate !
