### ISSUE TITLE
CodeXL and HIP

### ISSUE THREAD

**Issue by rjfnobre** [GPUOpen-Tools/CodeXL#49]
Is it possible to use the 'CodeXLGpuProfiler' to profile GPU occupancy on an AMD GPU (Fiji), for an application developed with HIP (instead of OpenCL)?

If it is possible, what are the paremeters I should pass to the 'CodeXLGpuProfiler' (other than the name of the compiled HIP application and the '-O' parameter for measuring GPU occupancy)?

In case 'CodeXLGpuProfiler' can not work with HIP, is there any tool that can do it?

HIP:
http://gpuopen.com/hip-release-0-86/
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP

**Comment by chesik-amd** [comment]
Yes, the CodeXL Profiler supports HIP.  Currently you can only collect occupancy data at the same time you collect performance counter data.  The command line options to use are:

CodeXLGpuProfiler --hsapmc --occupancy <application_name>

OR

CodeXLGpuProfiler -C -O <application_name>

**Comment by rjfnobre** [comment]
Thanks!!
It works!!

What flags do I have to additionaly use so that it also reports the proportion of time each kernel spent executing vector ALU operations (VALUBusy)?

It is only reporting:
Method; ExecutionOrder; ThreadID; GlobalWorkSize; WorkGroupSize; LocalMemSize; VGPRs; SGPRs; Wavefronts; VALUInsts; SALUInsts; VFetchInsts; SFetchInsts; VWriteInsts; FlatVMemInsts; FlatLDSInsts; SALUBusy; FetchSize; WriteSize; CacheHit

**Comment by chesik-amd** [comment]
You would need to pass a counter file to CodeXLGpuProfiler using the "-c <counterfile>" switch.

In the counter file, you would list each performance counter you want to collect, one per line in the file.

For a list of all the supported performance counters, simply run "CodeXLGpuProfiler --list".  It will output the full list of perfcounters on a per-device-family, per-API basis.  In a future version of CodeXL, you will be able to use "CodeXLGpuProfiler --list -o counterlist.txt" to have the full set of counters written to a file that you can edit and then pass to the profiler using the aforementioned -c switch.

The reason we can't collect a full set of counters by default is that there is a hardware-imposed limit on the number of perf counters that can be collected at the same time.  For OpenCL profiling, in most cases, the profiler is able to replay kernels in order to collect a full set of perfcounters.  For ROCm applications, the profiler is unable to do this, so we have to limit the counters collected at any given time.
